# Example/Documentation for the IG YML file
# https://fshschool.org/docs/sushi/configuration/#exhaustive-example

# Package name
# https://confluence.hl7.org/display/FHIR/NPM+Package+Specification#NPMPackageSpecification-Packagename
id: de.deutsche-diabetes-gesellschaft.fhir.ig.dmp-diabetes
canonical: http://deutsche-diabetes-gesellschaft.de/fhir/ig/dmp-diabetes
name: FHIR IG for Diabetes 2 DMP in Germany
title: "Diabetes DMP IG (R4)"
description: "This Implementation Guide aims at modelling the current Disease Management Program (DMP) documents used in Germany for Diabetes. The project is work in progress."
status: draft
license: CC-BY-SA-4.0
copyright: CC-BY-SA-4.0
jurisdiction: urn:iso:std:iso:3166#DEU
date: 2022-03-10
version: 0.0.1
fhirVersion: 4.0.1
copyrightYear: 2022+
# https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters -> Parameter: releaselabel
releaseLabel: CI Build
publisher:
  name: Open Connections
contact:
  name: Open Connections
  telecom:
    system: url
    value: https://www.open-connections.de/

dependencies:
  # ch.fhir.ig.ch-core: 2.0.0
  # kbv.basis: 1.3.0

pages:
  index.md:
    title: Home
  profiles.md:
    title: Profiles
  extensions.md:
    title: Extensions
  terminology.md:
    title: Terminology

# Parameters
# https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters

resources:
  CodeSystem/ch-ig-example-translation:
    name: DDG IG Example Translation
    exampleBoolean: false